walk_pattern:
  forward: 
    points: [[lx,lz,rx,rz,t],[],[]]
    std_vel: 1
  left_turn: 
    points: [[],[],[]]
    std_omega: 1
leg_sizes: [r1,r2]
moror_ids: [id1,id2,id3,id4,id5]
motor_params:
  - [a,b]
  - [a,b]
  - [a,b]
  - [a,b]
  - [a,b]
